name: AncientForge
version: 0.05
main: com.podts.ancientforge.P
author: [flatbmx, Will2233]
softdepend: [PermissionsEx, Essentials]

commands:
   magicitem:
      description: Gives person a random magic item.